export interface AirportRecord {
  code: string;
  city: string;
  country: string;
  name: string;
  keywords?: string;
}

export const GLOBAL_AIRPORTS: AirportRecord[] = [
  // --- NEPAL & SOUTH ASIA ---
  { code: 'KTM', city: 'Kathmandu', country: 'Nepal', name: 'Tribhuvan International Airport', keywords: 'kathmandu khatmandu khat ktm nepal tribhuvan bagmati' },
  { code: 'PKR', city: 'Pokhara', country: 'Nepal', name: 'Pokhara International Airport', keywords: 'pokhara pkr nepal gandaki' },
  { code: 'BWA', city: 'Bhairahawa / Siddharthanagar', country: 'Nepal', name: 'Gautam Buddha International Airport', keywords: 'bhairahawa bwa nepal lumbini buddha' },
  { code: 'BIR', city: 'Biratnagar', country: 'Nepal', name: 'Biratnagar Airport', keywords: 'biratnagar bir nepal morang' },
  { code: 'DAC', city: 'Dhaka', country: 'Bangladesh', name: 'Hazrat Shahjalal International Airport', keywords: 'dhaka dac bangladesh shahjalal' },
  { code: 'CGP', city: 'Chittagong', country: 'Bangladesh', name: 'Shah Amanat International Airport', keywords: 'chittagong cgp bangladesh chattogram' },
  { code: 'ZYL', city: 'Sylhet', country: 'Bangladesh', name: 'Osmani International Airport', keywords: 'sylhet zyl bangladesh osmani' },
  { code: 'CMB', city: 'Colombo', country: 'Sri Lanka', name: 'Bandaranaike International Airport', keywords: 'colombo cmb sri lanka bandaranaike katunayake' },
  { code: 'HRI', city: 'Hambantota', country: 'Sri Lanka', name: 'Mattala Rajapaksa International Airport', keywords: 'hambantota hri sri lanka mattala' },
  { code: 'MLE', city: 'Malé', country: 'Maldives', name: 'Velana International Airport', keywords: 'male mle maldives velana hulhule' },
  { code: 'GAN', city: 'Addu City', country: 'Maldives', name: 'Gan International Airport', keywords: 'gan addu city maldives' },
  { code: 'ISB', city: 'Islamabad', country: 'Pakistan', name: 'Islamabad International Airport', keywords: 'islamabad isb pakistan' },
  { code: 'KHI', city: 'Karachi', country: 'Pakistan', name: 'Jinnah International Airport', keywords: 'karachi khi pakistan jinnah' },
  { code: 'LHE', city: 'Lahore', country: 'Pakistan', name: 'Allama Iqbal International Airport', keywords: 'lahore lhe pakistan iqbal' },
  { code: 'PEW', city: 'Peshawar', country: 'Pakistan', name: 'Bacha Khan International Airport', keywords: 'peshawar pew pakistan' },
  { code: 'SKT', city: 'Sialkot', country: 'Pakistan', name: 'Sialkot International Airport', keywords: 'sialkot skt pakistan' },
  { code: 'PBH', city: 'Paro / Thimphu', country: 'Bhutan', name: 'Paro International Airport', keywords: 'bhutan paro pbh thimphu' },

  // --- INDIA (Comprehensive Major & Tier-2) ---
  { code: 'DEL', city: 'Delhi / New Delhi', country: 'India', name: 'Indira Gandhi International Airport', keywords: 'delhi new delhi igi igiat ndls ncr' },
  { code: 'BOM', city: 'Mumbai', country: 'India', name: 'Chhatrapati Shivaji Maharaj Intl', keywords: 'mumbai bombay csia csmit maharashtra' },
  { code: 'BLR', city: 'Bengaluru / Bangalore', country: 'India', name: 'Kempegowda International Airport', keywords: 'bangalore bengaluru kemp karnataka' },
  { code: 'MAA', city: 'Chennai / Madras', country: 'India', name: 'Chennai International Airport', keywords: 'chennai madras tamil nadu meenambakkam' },
  { code: 'HYD', city: 'Hyderabad', country: 'India', name: 'Rajiv Gandhi International Airport', keywords: 'hyderabad rgia secunderabad telangana' },
  { code: 'CCU', city: 'Kolkata', country: 'India', name: 'Netaji Subhash Chandra Bose Intl', keywords: 'kolkata calcutta dumdum west bengal' },
  { code: 'AMD', city: 'Ahmedabad', country: 'India', name: 'Sardar Vallabhbhai Patel Intl', keywords: 'ahmedabad gujarat svpi' },
  { code: 'COK', city: 'Kochi / Cochin', country: 'India', name: 'Cochin International Airport', keywords: 'kochi cochin kerala cial nedumbassery' },
  { code: 'ATQ', city: 'Amritsar', country: 'India', name: 'Sri Guru Ram Dass Jee Intl', keywords: 'amritsar punjab raja sansi golden temple' },
  { code: 'IXC', city: 'Chandigarh', country: 'India', name: 'Shaheed Bhagat Singh International', keywords: 'chandigarh mohali punjab haryana' },
  { code: 'PNQ', city: 'Pune', country: 'India', name: 'Pune Airport', keywords: 'pune maharashtra lohegaon' },
  { code: 'JAI', city: 'Jaipur', country: 'India', name: 'Jaipur International Airport', keywords: 'jaipur rajasthan sanganer pink city' },
  { code: 'LKO', city: 'Lucknow', country: 'India', name: 'Chaudhary Charan Singh Intl', keywords: 'lucknow up uttar pradesh amausi' },
  { code: 'GOI', city: 'Goa (Dabolim)', country: 'India', name: 'Goa Dabolim Airport', keywords: 'goa dabolim south goa' },
  { code: 'GOX', city: 'Goa (Mopa)', country: 'India', name: 'Manohar International Airport', keywords: 'goa mopa north goa manohar' },
  { code: 'TRV', city: 'Thiruvananthapuram', country: 'India', name: 'Trivandrum International Airport', keywords: 'thiruvananthapuram trivandrum kerala' },
  { code: 'PAT', city: 'Patna', country: 'India', name: 'Jay Prakash Narayan Airport', keywords: 'patna bihar' },
  { code: 'BBI', city: 'Bhubaneswar', country: 'India', name: 'Biju Patnaik International Airport', keywords: 'bhubaneswar odisha orissa' },
  { code: 'GAU', city: 'Guwahati', country: 'India', name: 'Lokpriya Gopinath Bordoloi Intl', keywords: 'guwahati assam borjhar northeast' },
  { code: 'SXR', city: 'Srinagar', country: 'India', name: 'Sheikh ul-Alam International Airport', keywords: 'srinagar kashmir j&k' },
  { code: 'IDR', city: 'Indore', country: 'India', name: 'Devi Ahilya Bai Holkar Airport', keywords: 'indore madhya pradesh mp' },
  { code: 'NAG', city: 'Nagpur', country: 'India', name: 'Dr. Babasaheb Ambedkar Intl', keywords: 'nagpur maharashtra' },
  { code: 'VNS', city: 'Varanasi / Banaras', country: 'India', name: 'Lal Bahadur Shastri Intl', keywords: 'varanasi banaras kashi up' },
  { code: 'VTZ', city: 'Visakhapatnam / Vizag', country: 'India', name: 'Visakhapatnam International Airport', keywords: 'visakhapatnam vizag andhra pradesh' },
  { code: 'CJB', city: 'Coimbatore', country: 'India', name: 'Coimbatore International Airport', keywords: 'coimbatore tamil nadu' },
  { code: 'IXR', city: 'Ranchi', country: 'India', name: 'Birsa Munda Airport', keywords: 'ranchi jharkhand' },
  { code: 'BDQ', city: 'Vadodara', country: 'India', name: 'Vadodara Airport', keywords: 'vadodara baroda gujarat' },
  { code: 'UDR', city: 'Udaipur', country: 'India', name: 'Maharana Pratap Airport', keywords: 'udaipur rajasthan dabok' },
  { code: 'IXE', city: 'Mangalore', country: 'India', name: 'Mangaluru International Airport', keywords: 'mangalore mangaluru karnataka bajpe' },
  { code: 'TRZ', city: 'Tiruchirappalli / Trichy', country: 'India', name: 'Tiruchirappalli International Airport', keywords: 'trichy tiruchirappalli tamil nadu' },
  { code: 'RPR', city: 'Raipur', country: 'India', name: 'Swami Vivekananda Airport', keywords: 'raipur chhattisgarh' },
  { code: 'IXB', city: 'Bagdogra / Siliguri', country: 'India', name: 'Bagdogra Airport', keywords: 'bagdogra siliguri darjeeling west bengal' },
  { code: 'DED', city: 'Dehradun / Rishikesh', country: 'India', name: 'Jolly Grant Airport', keywords: 'dehradun rishikesh uttarakhand jolly grant' },
  { code: 'IXJ', city: 'Jammu', country: 'India', name: 'Jammu Airport', keywords: 'jammu satwari j&k' },
  { code: 'IXL', city: 'Leh / Ladakh', country: 'India', name: 'Kushok Bakula Rimpochee Airport', keywords: 'leh ladakh' },
  { code: 'IXZ', city: 'Port Blair / Andaman', country: 'India', name: 'Veer Savarkar International Airport', keywords: 'port blair andaman nicobar islands' },
  { code: 'STV', city: 'Surat', country: 'India', name: 'Surat International Airport', keywords: 'surat gujarat' },
  { code: 'BHO', city: 'Bhopal', country: 'India', name: 'Raja Bhoj Airport', keywords: 'bhopal madhya pradesh' },
  { code: 'JDH', city: 'Jodhpur', country: 'India', name: 'Jodhpur Airport', keywords: 'jodhpur rajasthan' },
  { code: 'CNN', city: 'Kannur', country: 'India', name: 'Kannur International Airport', keywords: 'kannur kerala' },
  { code: 'CCJ', city: 'Kozhikode / Calicut', country: 'India', name: 'Calicut International Airport', keywords: 'calicut kozhikode karipur kerala' },
  { code: 'AYJ', city: 'Ayodhya', country: 'India', name: 'Maharishi Valmiki International Airport', keywords: 'ayodhya ram mandir up uttar pradesh faizabad' },

  // --- CANADA ---
  { code: 'YYZ', city: 'Toronto', country: 'Canada', name: 'Toronto Pearson International Airport', keywords: 'toronto yyz canada ontario pearson' },
  { code: 'YVR', city: 'Vancouver', country: 'Canada', name: 'Vancouver International Airport', keywords: 'vancouver yvr canada bc british columbia richmond' },
  { code: 'YUL', city: 'Montreal', country: 'Canada', name: 'Montréal-Trudeau International Airport', keywords: 'montreal yul canada quebec trudeau' },
  { code: 'YYC', city: 'Calgary', country: 'Canada', name: 'Calgary International Airport', keywords: 'calgary yyc canada alberta' },
  { code: 'YEG', city: 'Edmonton', country: 'Canada', name: 'Edmonton International Airport', keywords: 'edmonton yeg canada alberta' },
  { code: 'YOW', city: 'Ottawa', country: 'Canada', name: 'Ottawa Macdonald-Cartier International', keywords: 'ottawa yow canada ontario capital' },
  { code: 'YWG', city: 'Winnipeg', country: 'Canada', name: 'Winnipeg Richardson International Airport', keywords: 'winnipeg ywg canada manitoba' },
  { code: 'YHZ', city: 'Halifax', country: 'Canada', name: 'Halifax Stanfield International Airport', keywords: 'halifax yhz canada nova scotia' },
  { code: 'YYJ', city: 'Victoria', country: 'Canada', name: 'Victoria International Airport', keywords: 'victoria yyj canada bc vancouver island' },
  { code: 'YQB', city: 'Quebec City', country: 'Canada', name: 'Québec City Jean Lesage International', keywords: 'quebec yqb canada' },
  { code: 'YLW', city: 'Kelowna', country: 'Canada', name: 'Kelowna International Airport', keywords: 'kelowna ylw canada bc okanagan' },
  { code: 'YTZ', city: 'Toronto (City)', country: 'Canada', name: 'Billy Bishop Toronto City Airport', keywords: 'billy bishop island toronto ytz canada' },
  { code: 'YXE', city: 'Saskatoon', country: 'Canada', name: 'Saskatoon John G. Diefenbaker Intl', keywords: 'saskatoon yxe saskatchewan canada' },
  { code: 'YQR', city: 'Regina', country: 'Canada', name: 'Regina International Airport', keywords: 'regina yqr saskatchewan canada' },
  { code: 'YYT', city: "St. John's", country: 'Canada', name: "St. John's International Airport", keywords: 'st johns newfoundland yyt canada' },

  // --- UNITED STATES ---
  { code: 'JFK', city: 'New York', country: 'USA', name: 'John F. Kennedy International Airport', keywords: 'new york jfk nyc usa queens kennedy' },
  { code: 'EWR', city: 'Newark / New York', country: 'USA', name: 'Newark Liberty International Airport', keywords: 'newark new york ewr nyc usa new jersey' },
  { code: 'LGA', city: 'New York (LaGuardia)', country: 'USA', name: 'LaGuardia Airport', keywords: 'laguardia lga new york nyc usa' },
  { code: 'LAX', city: 'Los Angeles', country: 'USA', name: 'Los Angeles International Airport', keywords: 'los angeles lax california usa' },
  { code: 'SFO', city: 'San Francisco', country: 'USA', name: 'San Francisco International Airport', keywords: 'san francisco sfo california usa bay area' },
  { code: 'ORD', city: 'Chicago (O\'Hare)', country: 'USA', name: 'O\'Hare International Airport', keywords: 'chicago ord ohare illinois usa' },
  { code: 'MDW', city: 'Chicago (Midway)', country: 'USA', name: 'Chicago Midway International Airport', keywords: 'chicago mdw midway illinois usa' },
  { code: 'SEA', city: 'Seattle', country: 'USA', name: 'Seattle-Tacoma International Airport', keywords: 'seattle sea seatac washington usa' },
  { code: 'MIA', city: 'Miami', country: 'USA', name: 'Miami International Airport', keywords: 'miami mia florida usa' },
  { code: 'FLL', city: 'Fort Lauderdale', country: 'USA', name: 'Fort Lauderdale-Hollywood Intl', keywords: 'fort lauderdale fll florida miami usa' },
  { code: 'BOS', city: 'Boston', country: 'USA', name: 'Boston Logan International Airport', keywords: 'boston bos logan massachusetts usa' },
  { code: 'DFW', city: 'Dallas / Fort Worth', country: 'USA', name: 'Dallas/Fort Worth International', keywords: 'dallas dfw texas usa fort worth' },
  { code: 'DAL', city: 'Dallas (Love Field)', country: 'USA', name: 'Dallas Love Field', keywords: 'dallas love field dal texas usa' },
  { code: 'IAH', city: 'Houston (George Bush)', country: 'USA', name: 'George Bush Intercontinental Airport', keywords: 'houston iah texas george bush usa' },
  { code: 'HOU', city: 'Houston (Hobby)', country: 'USA', name: 'William P. Hobby Airport', keywords: 'houston hobby hou texas usa' },
  { code: 'ATL', city: 'Atlanta', country: 'USA', name: 'Hartsfield-Jackson Atlanta Intl', keywords: 'atlanta atl georgia usa hartsfield' },
  { code: 'LAS', city: 'Las Vegas', country: 'USA', name: 'Harry Reid International Airport', keywords: 'las vegas las mccarran nevada usa' },
  { code: 'MCO', city: 'Orlando', country: 'USA', name: 'Orlando International Airport', keywords: 'orlando mco florida disney usa' },
  { code: 'DEN', city: 'Denver', country: 'USA', name: 'Denver International Airport', keywords: 'denver den colorado usa' },
  { code: 'PHX', city: 'Phoenix', country: 'USA', name: 'Phoenix Sky Harbor International', keywords: 'phoenix phx arizona sky harbor usa' },
  { code: 'IAD', city: 'Washington D.C. (Dulles)', country: 'USA', name: 'Washington Dulles International Airport', keywords: 'washington dc iad dulles virginia usa' },
  { code: 'DCA', city: 'Washington D.C. (Reagan)', country: 'USA', name: 'Ronald Reagan Washington National', keywords: 'washington dc dca reagan national usa' },
  { code: 'SAN', city: 'San Diego', country: 'USA', name: 'San Diego International Airport', keywords: 'san diego san california usa' },
  { code: 'SJC', city: 'San Jose', country: 'USA', name: 'Norman Y. Mineta San Jose Intl', keywords: 'san jose sjc silicon valley california usa' },
  { code: 'OAK', city: 'Oakland / Bay Area', country: 'USA', name: 'Oakland International Airport', keywords: 'oakland oak san francisco bay area california usa' },
  { code: 'PDX', city: 'Portland', country: 'USA', name: 'Portland International Airport', keywords: 'portland pdx oregon usa' },
  { code: 'PHL', city: 'Philadelphia', country: 'USA', name: 'Philadelphia International Airport', keywords: 'philadelphia phl pennsylvania usa' },
  { code: 'CLT', city: 'Charlotte', country: 'USA', name: 'Charlotte Douglas International Airport', keywords: 'charlotte clt north carolina usa' },
  { code: 'DTW', city: 'Detroit', country: 'USA', name: 'Detroit Metropolitan Wayne County', keywords: 'detroit dtw michigan usa' },
  { code: 'MSP', city: 'Minneapolis / St. Paul', country: 'USA', name: 'Minneapolis-Saint Paul International', keywords: 'minneapolis msp st paul minnesota usa' },
  { code: 'TPA', city: 'Tampa', country: 'USA', name: 'Tampa International Airport', keywords: 'tampa tpa florida usa' },
  { code: 'SLC', city: 'Salt Lake City', country: 'USA', name: 'Salt Lake City International Airport', keywords: 'salt lake city slc utah usa' },
  { code: 'BNA', city: 'Nashville', country: 'USA', name: 'Nashville International Airport', keywords: 'nashville bna tennessee usa' },
  { code: 'AUS', city: 'Austin', country: 'USA', name: 'Austin-Bergstrom International Airport', keywords: 'austin aus texas usa' },
  { code: 'RDU', city: 'Raleigh / Durham', country: 'USA', name: 'Raleigh-Durham International Airport', keywords: 'raleigh durham rdu north carolina usa' },
  { code: 'HNL', city: 'Honolulu', country: 'USA', name: 'Daniel K. Inouye International Airport', keywords: 'honolulu hnl hawaii oahu usa' },
  { code: 'ANC', city: 'Anchorage', country: 'USA', name: 'Ted Stevens Anchorage International', keywords: 'anchorage anc alaska usa' },

  // --- UNITED KINGDOM & EUROPE ---
  { code: 'LHR', city: 'London (Heathrow)', country: 'United Kingdom', name: 'Heathrow Airport', keywords: 'london lhr heathrow uk england europe' },
  { code: 'LGW', city: 'London (Gatwick)', country: 'United Kingdom', name: 'Gatwick Airport', keywords: 'london lgw gatwick uk england europe' },
  { code: 'STN', city: 'London (Stansted)', country: 'United Kingdom', name: 'London Stansted Airport', keywords: 'london stn stansted uk england' },
  { code: 'LTN', city: 'London (Luton)', country: 'United Kingdom', name: 'London Luton Airport', keywords: 'london ltn luton uk england' },
  { code: 'LCY', city: 'London (City)', country: 'United Kingdom', name: 'London City Airport', keywords: 'london lcy city uk england' },
  { code: 'MAN', city: 'Manchester', country: 'United Kingdom', name: 'Manchester Airport', keywords: 'manchester man uk england europe' },
  { code: 'BHX', city: 'Birmingham', country: 'United Kingdom', name: 'Birmingham Airport', keywords: 'birmingham bhx uk england' },
  { code: 'EDI', city: 'Edinburgh', country: 'United Kingdom', name: 'Edinburgh Airport', keywords: 'edinburgh edi scotland uk' },
  { code: 'GLA', city: 'Glasgow', country: 'United Kingdom', name: 'Glasgow Airport', keywords: 'glasgow gla scotland uk' },
  { code: 'DUB', city: 'Dublin', country: 'Ireland', name: 'Dublin Airport', keywords: 'dublin dub ireland europe' },
  { code: 'CDG', city: 'Paris (Charles de Gaulle)', country: 'France', name: 'Charles de Gaulle Airport', keywords: 'paris cdg france roissy europe' },
  { code: 'ORY', city: 'Paris (Orly)', country: 'France', name: 'Paris Orly Airport', keywords: 'paris ory orly france europe' },
  { code: 'NCE', city: 'Nice', country: 'France', name: 'Nice Côte d\'Azur Airport', keywords: 'nice nce france french riviera europe' },
  { code: 'LYS', city: 'Lyon', country: 'France', name: 'Lyon-Saint Exupéry Airport', keywords: 'lyon lys france europe' },
  { code: 'MRS', city: 'Marseille', country: 'France', name: 'Marseille Provence Airport', keywords: 'marseille mrs france europe' },
  { code: 'AMS', city: 'Amsterdam', country: 'Netherlands', name: 'Amsterdam Airport Schiphol', keywords: 'amsterdam ams schiphol netherlands holland europe' },
  { code: 'FRA', city: 'Frankfurt', country: 'Germany', name: 'Frankfurt Airport', keywords: 'frankfurt fra germany main europe' },
  { code: 'MUC', city: 'Munich', country: 'Germany', name: 'Munich Airport', keywords: 'munich muc germany bayern bavaria europe' },
  { code: 'BER', city: 'Berlin', country: 'Germany', name: 'Berlin Brandenburg Airport', keywords: 'berlin ber brandenburg germany europe' },
  { code: 'HAM', city: 'Hamburg', country: 'Germany', name: 'Hamburg Airport', keywords: 'hamburg ham germany europe' },
  { code: 'DUS', city: 'Dusseldorf', country: 'Germany', name: 'Düsseldorf Airport', keywords: 'dusseldorf dusseldorf dus germany europe' },
  { code: 'FCO', city: 'Rome (Fiumicino)', country: 'Italy', name: 'Leonardo da Vinci–Fiumicino Airport', keywords: 'rome fco fiumicino italy italia europe' },
  { code: 'CIA', city: 'Rome (Ciampino)', country: 'Italy', name: 'Rome Ciampino Airport', keywords: 'rome cia ciampino italy europe' },
  { code: 'MXP', city: 'Milan (Malpensa)', country: 'Italy', name: 'Milan Malpensa Airport', keywords: 'milan mxp malpensa italy lombardy europe' },
  { code: 'LIN', city: 'Milan (Linate)', country: 'Italy', name: 'Milan Linate Airport', keywords: 'milan lin linate italy europe' },
  { code: 'VCE', city: 'Venice', country: 'Italy', name: 'Venice Marco Polo Airport', keywords: 'venice vce marco polo marco polo italy europe' },
  { code: 'NAP', city: 'Naples', country: 'Italy', name: 'Naples International Airport', keywords: 'naples nap napoli italy europe' },
  { code: 'FLR', city: 'Florence', country: 'Italy', name: 'Florence Airport', keywords: 'florence flr firenze tuscany italy europe' },
  { code: 'MAD', city: 'Madrid', country: 'Spain', name: 'Adolfo Suárez Madrid–Barajas Airport', keywords: 'madrid mad barajas spain espana europe' },
  { code: 'BCN', city: 'Barcelona', country: 'Spain', name: 'Josep Tarradellas Barcelona-El Prat', keywords: 'barcelona bcn el prat catalonia spain espana europe' },
  { code: 'AGP', city: 'Malaga', country: 'Spain', name: 'Málaga-Costa del Sol Airport', keywords: 'malaga agp costa del sol spain europe' },
  { code: 'PMI', city: 'Palma de Mallorca', country: 'Spain', name: 'Palma de Mallorca Airport', keywords: 'palma de mallorca pmi majorca spain europe' },
  { code: 'VLC', city: 'Valencia', country: 'Spain', name: 'Valencia Airport', keywords: 'valencia vlc spain europe' },
  { code: 'ZRH', city: 'Zurich', country: 'Switzerland', name: 'Zurich Airport', keywords: 'zurich zrh switzerland kloten swiss europe' },
  { code: 'GVA', city: 'Geneva', country: 'Switzerland', name: 'Geneva Airport', keywords: 'geneva gva switzerland swiss europe' },
  { code: 'BSL', city: 'Basel / Mulhouse', country: 'Switzerland', name: 'EuroAirport Basel Mulhouse Freiburg', keywords: 'basel bsl mulhouse switzerland france europe' },
  { code: 'VIE', city: 'Vienna', country: 'Austria', name: 'Vienna International Airport', keywords: 'vienna vie wien austria europe' },
  { code: 'BRU', city: 'Brussels', country: 'Belgium', name: 'Brussels Airport', keywords: 'brussels bru belgium zaventem europe' },
  { code: 'LIS', city: 'Lisbon', country: 'Portugal', name: 'Humberto Delgado Airport', keywords: 'lisbon lis portugal portela europe' },
  { code: 'OPO', city: 'Porto', country: 'Portugal', name: 'Francisco Sá Carneiro Airport', keywords: 'porto opo portugal europe' },
  { code: 'ATH', city: 'Athens', country: 'Greece', name: 'Eleftherios Venizelos Airport', keywords: 'athens ath greece hellas europe' },
  { code: 'HER', city: 'Heraklion / Crete', country: 'Greece', name: 'Heraklion International Airport', keywords: 'heraklion her crete greece europe' },
  { code: 'JTR', city: 'Santorini', country: 'Greece', name: 'Santorini Airport', keywords: 'santorini jtr thira greece europe' },
  { code: 'JMK', city: 'Mykonos', country: 'Greece', name: 'Mykonos Airport', keywords: 'mykonos jmk greece europe' },
  { code: 'CPH', city: 'Copenhagen', country: 'Denmark', name: 'Copenhagen Airport', keywords: 'copenhagen cph denmark kastrup scandinavia europe' },
  { code: 'ARN', city: 'Stockholm (Arlanda)', country: 'Sweden', name: 'Stockholm Arlanda Airport', keywords: 'stockholm arn arlanda sweden scandinavia europe' },
  { code: 'OSL', city: 'Oslo', country: 'Norway', name: 'Oslo Airport Gardermoen', keywords: 'oslo osl gardermoen norway scandinavia europe' },
  { code: 'HEL', city: 'Helsinki', country: 'Finland', name: 'Helsinki Airport', keywords: 'helsinki hel vantaa finland europe' },
  { code: 'WAW', city: 'Warsaw', country: 'Poland', name: 'Warsaw Chopin Airport', keywords: 'warsaw waw chopin poland europe' },
  { code: 'KRK', city: 'Krakow', country: 'Poland', name: 'Kraków John Paul II International', keywords: 'krakow krk poland balice europe' },
  { code: 'PRG', city: 'Prague', country: 'Czech Republic', name: 'Václav Havel Airport Prague', keywords: 'prague prg czech ruzyne europe' },
  { code: 'BUD', city: 'Budapest', country: 'Hungary', name: 'Budapest Ferenc Liszt International', keywords: 'budapest bud hungary ferihegy europe' },
  { code: 'OTP', city: 'Bucharest', country: 'Romania', name: 'Henri Coandă International Airport', keywords: 'bucharest otp otopeni romania europe' },
  { code: 'IST', city: 'Istanbul', country: 'Turkey', name: 'Istanbul Airport', keywords: 'istanbul ist turkey turkiye europe asia' },
  { code: 'SAW', city: 'Istanbul (Sabiha)', country: 'Turkey', name: 'Sabiha Gökçen International Airport', keywords: 'istanbul saw sabiha gokcen turkey turkiye' },
  { code: 'AYT', city: 'Antalya', country: 'Turkey', name: 'Antalya Airport', keywords: 'antalya ayt turkey mediterranean' },

  // --- MIDDLE EAST ---
  { code: 'DXB', city: 'Dubai', country: 'United Arab Emirates', name: 'Dubai International Airport', keywords: 'dubai dxb uae emirates middle east' },
  { code: 'DWC', city: 'Dubai (Al Maktoum)', country: 'United Arab Emirates', name: 'Al Maktoum International Airport', keywords: 'dubai dwc al maktoum uae' },
  { code: 'AUH', city: 'Abu Dhabi', country: 'United Arab Emirates', name: 'Zayed International Airport', keywords: 'abu dhabi auh uae zayed' },
  { code: 'SHJ', city: 'Sharjah', country: 'United Arab Emirates', name: 'Sharjah International Airport', keywords: 'sharjah shj uae air arabia' },
  { code: 'DOH', city: 'Doha', country: 'Qatar', name: 'Hamad International Airport', keywords: 'doha doh qatar hamad qatar airways' },
  { code: 'RUH', city: 'Riyadh', country: 'Saudi Arabia', name: 'King Khalid International Airport', keywords: 'riyadh ruh saudi arabia ksa khalid' },
  { code: 'JED', city: 'Jeddah', country: 'Saudi Arabia', name: 'King Abdulaziz International Airport', keywords: 'jeddah jed mecca makkah saudi arabia hajj umrah' },
  { code: 'MED', city: 'Medina', country: 'Saudi Arabia', name: 'Prince Mohammad Bin Abdulaziz Intl', keywords: 'medina med madinah saudi arabia' },
  { code: 'DMM', city: 'Dammam', country: 'Saudi Arabia', name: 'King Fahd International Airport', keywords: 'dammam dmm saudi arabia fahd' },
  { code: 'BAH', city: 'Bahrain / Manama', country: 'Bahrain', name: 'Bahrain International Airport', keywords: 'bahrain bah manama gulf' },
  { code: 'KWI', city: 'Kuwait City', country: 'Kuwait', name: 'Kuwait International Airport', keywords: 'kuwait kwi kuwait city' },
  { code: 'MCT', city: 'Muscat', country: 'Oman', name: 'Muscat International Airport', keywords: 'muscat mct oman seeb' },
  { code: 'AMM', city: 'Amman', country: 'Jordan', name: 'Queen Alia International Airport', keywords: 'amman amm jordan alia' },
  { code: 'BEY', city: 'Beirut', country: 'Lebanon', name: 'Beirut-Rafic Hariri International', keywords: 'beirut bey lebanon hariri' },
  { code: 'TLV', city: 'Tel Aviv', country: 'Israel', name: 'Ben Gurion Airport', keywords: 'tel aviv tlv israel ben gurion' },

  // --- ASIA PACIFIC & EAST ASIA ---
  { code: 'SIN', city: 'Singapore', country: 'Singapore', name: 'Singapore Changi Airport', keywords: 'singapore sin changi asia jewel' },
  { code: 'BKK', city: 'Bangkok (Suvarnabhumi)', country: 'Thailand', name: 'Suvarnabhumi Airport', keywords: 'bangkok bkk suvarnabhumi thailand southeast asia' },
  { code: 'DMK', city: 'Bangkok (Don Mueang)', country: 'Thailand', name: 'Don Mueang International Airport', keywords: 'bangkok dmk don mueang thailand' },
  { code: 'HKT', city: 'Phuket', country: 'Thailand', name: 'Phuket International Airport', keywords: 'phuket hkt thailand andaman' },
  { code: 'CNX', city: 'Chiang Mai', country: 'Thailand', name: 'Chiang Mai International Airport', keywords: 'chiang mai cnx thailand' },
  { code: 'KUL', city: 'Kuala Lumpur', country: 'Malaysia', name: 'Kuala Lumpur International Airport', keywords: 'kuala lumpur kul malaysia klia sepang' },
  { code: 'PEN', city: 'Penang', country: 'Malaysia', name: 'Penang International Airport', keywords: 'penang pen georgetown malaysia' },
  { code: 'DPS', city: 'Bali / Denpasar', country: 'Indonesia', name: 'Ngurah Rai International Airport', keywords: 'bali dps denpasar indonesia ngurah rai' },
  { code: 'CGK', city: 'Jakarta', country: 'Indonesia', name: 'Soekarno-Hatta International Airport', keywords: 'jakarta cgk indonesia soekarno hatta cengkareng' },
  { code: 'SUB', city: 'Surabaya', country: 'Indonesia', name: 'Juanda International Airport', keywords: 'surabaya sub indonesia juanda' },
  { code: 'MNL', city: 'Manila', country: 'Philippines', name: 'Ninoy Aquino International Airport', keywords: 'manila mnl naia philippines' },
  { code: 'CEB', city: 'Cebu', country: 'Philippines', name: 'Mactan-Cebu International Airport', keywords: 'cebu ceb mactan philippines' },
  { code: 'SGN', city: 'Ho Chi Minh City / Saigon', country: 'Vietnam', name: 'Tan Son Nhat International Airport', keywords: 'ho chi minh sgn saigon vietnam tan son nhat' },
  { code: 'HAN', city: 'Hanoi', country: 'Vietnam', name: 'Noi Bai International Airport', keywords: 'hanoi han noi bai vietnam' },
  { code: 'DAD', city: 'Da Nang', country: 'Vietnam', name: 'Da Nang International Airport', keywords: 'da nang dad vietnam' },
  { code: 'HKG', city: 'Hong Kong', country: 'Hong Kong', name: 'Hong Kong International Airport', keywords: 'hong kong hkg chek lap kok' },
  { code: 'MFM', city: 'Macau', country: 'Macau', name: 'Macau International Airport', keywords: 'macau mfm macao' },
  { code: 'TPE', city: 'Taipei (Taoyuan)', country: 'Taiwan', name: 'Taiwan Taoyuan International Airport', keywords: 'taipei tpe taoyuan taiwan' },
  { code: 'TSA', city: 'Taipei (Songshan)', country: 'Taiwan', name: 'Taipei Songshan Airport', keywords: 'taipei tsa songshan taiwan' },
  { code: 'HND', city: 'Tokyo (Haneda)', country: 'Japan', name: 'Tokyo Haneda Airport', keywords: 'tokyo hnd haneda japan ota' },
  { code: 'NRT', city: 'Tokyo (Narita)', country: 'Japan', name: 'Narita International Airport', keywords: 'tokyo nrt narita japan chiba' },
  { code: 'KIX', city: 'Osaka (Kansai)', country: 'Japan', name: 'Kansai International Airport', keywords: 'osaka kix kansai japan' },
  { code: 'ITM', city: 'Osaka (Itami)', country: 'Japan', name: 'Itami Airport', keywords: 'osaka itm itami osaka international japan' },
  { code: 'NGO', city: 'Nagoya', country: 'Japan', name: 'Chubu Centrair International', keywords: 'nagoya ngo centrair chubu japan' },
  { code: 'FUK', city: 'Fukuoka', country: 'Japan', name: 'Fukuoka Airport', keywords: 'fukuoka fuk kyushu japan' },
  { code: 'CTS', city: 'Sapporo', country: 'Japan', name: 'New Chitose Airport', keywords: 'sapporo cts hokkaido new chitose japan' },
  { code: 'ICN', city: 'Seoul (Incheon)', country: 'South Korea', name: 'Incheon International Airport', keywords: 'seoul icn incheon korea' },
  { code: 'GMP', city: 'Seoul (Gimpo)', country: 'South Korea', name: 'Gimpo International Airport', keywords: 'seoul gmp gimpo korea' },
  { code: 'PUS', city: 'Busan', country: 'South Korea', name: 'Gimhae International Airport', keywords: 'busan pus gimhae korea' },
  { code: 'PEK', city: 'Beijing (Capital)', country: 'China', name: 'Beijing Capital International Airport', keywords: 'beijing pek capital china bcai' },
  { code: 'PKX', city: 'Beijing (Daxing)', country: 'China', name: 'Beijing Daxing International Airport', keywords: 'beijing pkx daxing china' },
  { code: 'PVG', city: 'Shanghai (Pudong)', country: 'China', name: 'Shanghai Pudong International', keywords: 'shanghai pvg pudong china' },
  { code: 'SHA', city: 'Shanghai (Hongqiao)', country: 'China', name: 'Shanghai Hongqiao International', keywords: 'shanghai sha hongqiao china' },
  { code: 'CAN', city: 'Guangzhou', country: 'China', name: 'Guangzhou Baiyun International', keywords: 'guangzhou can baiyun guangdong china' },
  { code: 'SZX', city: 'Shenzhen', country: 'China', name: 'Shenzhen Bao\'an International', keywords: 'shenzhen szx baoan china' },
  { code: 'CTU', city: 'Chengdu', country: 'China', name: 'Chengdu Shuangliu International', keywords: 'chengdu ctu sichuan china' },
  { code: 'TFU', city: 'Chengdu (Tianfu)', country: 'China', name: 'Chengdu Tianfu International', keywords: 'chengdu tfu tianfu sichuan china' },

  // --- AUSTRALIA & NEW ZEALAND ---
  { code: 'SYD', city: 'Sydney', country: 'Australia', name: 'Sydney Kingsford Smith Airport', keywords: 'sydney syd nsw australia kingsford smith' },
  { code: 'MEL', city: 'Melbourne', country: 'Australia', name: 'Melbourne Airport', keywords: 'melbourne mel tullamarine victoria australia' },
  { code: 'BNE', city: 'Brisbane', country: 'Australia', name: 'Brisbane Airport', keywords: 'brisbane bne queensland australia' },
  { code: 'PER', city: 'Perth', country: 'Australia', name: 'Perth Airport', keywords: 'perth per western australia' },
  { code: 'ADL', city: 'Adelaide', country: 'Australia', name: 'Adelaide Airport', keywords: 'adelaide adl south australia' },
  { code: 'OOL', city: 'Gold Coast', country: 'Australia', name: 'Gold Coast Airport', keywords: 'gold coast ool coolangatta queensland australia' },
  { code: 'CBR', city: 'Canberra', country: 'Australia', name: 'Canberra Airport', keywords: 'canberra cbr act capital australia' },
  { code: 'CNS', city: 'Cairns', country: 'Australia', name: 'Cairns Airport', keywords: 'cairns cns great barrier reef queensland australia' },
  { code: 'DRW', city: 'Darwin', country: 'Australia', name: 'Darwin International Airport', keywords: 'darwin drw northern territory australia' },
  { code: 'AKL', city: 'Auckland', country: 'New Zealand', name: 'Auckland Airport', keywords: 'auckland akl new zealand mangere nz' },
  { code: 'CHC', city: 'Christchurch', country: 'New Zealand', name: 'Christchurch International Airport', keywords: 'christchurch chc south island new zealand nz' },
  { code: 'WLG', city: 'Wellington', country: 'New Zealand', name: 'Wellington International Airport', keywords: 'wellington wlg capital new zealand nz' },
  { code: 'ZQN', city: 'Queenstown', country: 'New Zealand', name: 'Queenstown Airport', keywords: 'queenstown zqn new zealand otago nz' },
  { code: 'NAN', city: 'Nadi / Suva', country: 'Fiji', name: 'Nadi International Airport', keywords: 'nadi nan fiji suva south pacific' },

  // --- AFRICA ---
  { code: 'CAI', city: 'Cairo', country: 'Egypt', name: 'Cairo International Airport', keywords: 'cairo cai egypt pyramids nile africa' },
  { code: 'HRG', city: 'Hurghada', country: 'Egypt', name: 'Hurghada International Airport', keywords: 'hurghada hrg egypt red sea' },
  { code: 'SSH', city: 'Sharm El Sheikh', country: 'Egypt', name: 'Sharm El Sheikh International', keywords: 'sharm el sheikh ssh egypt sinai' },
  { code: 'JNB', city: 'Johannesburg', country: 'South Africa', name: 'O. R. Tambo International Airport', keywords: 'johannesburg jnb tambo south africa gauteng' },
  { code: 'CPT', city: 'Cape Town', country: 'South Africa', name: 'Cape Town International Airport', keywords: 'cape town cpt western cape south africa table mountain' },
  { code: 'DUR', city: 'Durban', country: 'South Africa', name: 'King Shaka International Airport', keywords: 'durban dur king shaka kwazulu natal south africa' },
  { code: 'NBO', city: 'Nairobi', country: 'Kenya', name: 'Jomo Kenyatta International Airport', keywords: 'nairobi nbo kenyatta kenya east africa safari' },
  { code: 'MBA', city: 'Mombasa', country: 'Kenya', name: 'Moi International Airport', keywords: 'mombasa mba moi kenya coast' },
  { code: 'ADD', city: 'Addis Ababa', country: 'Ethiopia', name: 'Bole International Airport', keywords: 'addis ababa add bole ethiopian airlines horn of africa' },
  { code: 'CMN', city: 'Casablanca', country: 'Morocco', name: 'Mohammed V International Airport', keywords: 'casablanca cmn morocco mohammed v north africa' },
  { code: 'RAK', city: 'Marrakech', country: 'Morocco', name: 'Marrakesh Menara Airport', keywords: 'marrakech rak menara morocco' },
  { code: 'LOS', city: 'Lagos', country: 'Nigeria', name: 'Murtala Muhammed International Airport', keywords: 'lagos los murtala muhammed nigeria west africa' },
  { code: 'ACC', city: 'Accra', country: 'Ghana', name: 'Kotoka International Airport', keywords: 'accra acc kotoka ghana west africa' },
  { code: 'EBB', city: 'Entebbe / Kampala', country: 'Uganda', name: 'Entebbe International Airport', keywords: 'entebbe ebb kampala uganda lake victoria' },
  { code: 'DAR', city: 'Dar es Salaam', country: 'Tanzania', name: 'Julius Nyerere International', keywords: 'dar es salaam dar nyerere tanzania zanzibar' },
  { code: 'ZNZ', city: 'Zanzibar', country: 'Tanzania', name: 'Abeid Amani Karume International', keywords: 'zanzibar znz tanzania spice island' },
  { code: 'MRU', city: 'Mauritius', country: 'Mauritius', name: 'Sir Seewoosagur Ramgoolam Intl', keywords: 'mauritius mru port louis indian ocean' },
  { code: 'SEZ', city: 'Seychelles / Mahe', country: 'Seychelles', name: 'Seychelles International Airport', keywords: 'seychelles sez mahe victoria indian ocean' },

  // --- LATIN AMERICA & CARIBBEAN ---
  { code: 'MEX', city: 'Mexico City', country: 'Mexico', name: 'Mexico City International (Benito Juárez)', keywords: 'mexico city mex cdmx benito juarez' },
  { code: 'CUN', city: 'Cancun', country: 'Mexico', name: 'Cancún International Airport', keywords: 'cancun cun quintana roo riviera maya mexico' },
  { code: 'GDL', city: 'Guadalajara', country: 'Mexico', name: 'Guadalajara International Airport', keywords: 'guadalajara gdl jalisco mexico' },
  { code: 'PTY', city: 'Panama City', country: 'Panama', name: 'Tocumen International Airport', keywords: 'panama city pty tocumen copa americas' },
  { code: 'BOG', city: 'Bogota', country: 'Colombia', name: 'El Dorado International Airport', keywords: 'bogota bog el dorado colombia' },
  { code: 'MDE', city: 'Medellin', country: 'Colombia', name: 'José María Córdova International', keywords: 'medellin mde rionegro colombia' },
  { code: 'LIM', city: 'Lima', country: 'Peru', name: 'Jorge Chávez International Airport', keywords: 'lima lim jorge chavez peru callao machu picchu' },
  { code: 'CUZ', city: 'Cusco', country: 'Peru', name: 'Alejandro Velasco Astete International', keywords: 'cusco cuz cuzco peru machu picchu' },
  { code: 'SCL', city: 'Santiago', country: 'Chile', name: 'Arturo Merino Benítez International', keywords: 'santiago scl pudahuel chile' },
  { code: 'EZE', city: 'Buenos Aires (Ezeiza)', country: 'Argentina', name: 'Ministro Pistarini International', keywords: 'buenos aires eze ezeiza argentina' },
  { code: 'AEP', city: 'Buenos Aires (Aeroparque)', country: 'Argentina', name: 'Aeroparque Jorge Newbery', keywords: 'buenos aires aep aeroparque argentina' },
  { code: 'GRU', city: 'Sao Paulo (Guarulhos)', country: 'Brazil', name: 'São Paulo/Guarulhos International', keywords: 'sao paulo gru guarulhos brazil brasil' },
  { code: 'CGH', city: 'Sao Paulo (Congonhas)', country: 'Brazil', name: 'Congonhas Airport', keywords: 'sao paulo cgh congonhas brazil brasil' },
  { code: 'GIG', city: 'Rio de Janeiro (Galeao)', country: 'Brazil', name: 'Rio de Janeiro/Galeão International', keywords: 'rio de janeiro gig galeao tom jobim brazil brasil' },
  { code: 'SDQ', city: 'Santo Domingo', country: 'Dominican Republic', name: 'Las Américas International Airport', keywords: 'santo domingo sdq dominican republic carib' },
  { code: 'PUJ', city: 'Punta Cana', country: 'Dominican Republic', name: 'Punta Cana International Airport', keywords: 'punta cana puj dominican republic caribbean resort' },
  { code: 'SJU', city: 'San Juan', country: 'Puerto Rico', name: 'Luis Muñoz Marín International', keywords: 'san juan sju puerto rico usa caribbean' },
  { code: 'MBJ', city: 'Montego Bay', country: 'Jamaica', name: 'Sangster International Airport', keywords: 'montego bay mbj jamaica sangster caribbean' },
  { code: 'KIN', city: 'Kingston', country: 'Jamaica', name: 'Norman Manley International Airport', keywords: 'kingston kin jamaica' },
  { code: 'NAS', city: 'Nassau', country: 'Bahamas', name: 'Lynden Pindling International Airport', keywords: 'nassau nas bahamas lynden pindling' },
  { code: 'HAV', city: 'Havana', country: 'Cuba', name: 'José Martí International Airport', keywords: 'havana hav jose marti cuba' },
  { code: 'SJO', city: 'San Jose', country: 'Costa Rica', name: 'Juan Santamaría International Airport', keywords: 'san jose sjo juan santamaria costa rica' },
  { code: 'UIO', city: 'Quito', country: 'Ecuador', name: 'Mariscal Sucre International Airport', keywords: 'quito uio ecuador mariscal sucre andes' },
  { code: 'GYE', city: 'Guayaquil', country: 'Ecuador', name: 'José Joaquín de Olmedo International', keywords: 'guayaquil gye ecuador' },
  { code: 'GUA', city: 'Guatemala City', country: 'Guatemala', name: 'La Aurora International Airport', keywords: 'guatemala city gua la aurora' },
  { code: 'SAL', city: 'San Salvador', country: 'El Salvador', name: 'El Salvador International Airport', keywords: 'san salvador sal monseñor romero el salvador' },
];
